source 'https://github.com/shopping1985/ZDSpec.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '10.0'

target 'MMDHome_Example' do
  pod 'MMDHome', :path => '../'

  target 'MMDHome_Tests' do
    inherit! :search_paths

    
  end
end
